spring:
  datasource:
    url: jdbc:mysql://${MYSQL_PROD_URL}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_PROD_USER}
    password: ${MYSQL_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      redirect-url: https://splanet.co.kr/login/oauth2/code/kakao
  config:
    import: env.properties