global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'springboot'
    static_configs:
      - targets: ['springboot:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']